services:
  db:
    image: postgres
    restart: always
    env_file:
      - env.properties
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - '5432:5432'
  server:
    profiles: [prod]
    env_file:
      - env.properties
    ports:
      - '8080:8080'
    environment:
        SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/${DB_NAME}
        SPRING_DATASOURCE_USERNAME: ${DB_USER}
        SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}
    depends_on:
      - db
